### ISSUE TITLE
Norme di Progetto - Processi di Supporto (Gestione della Qualità)

### ISSUE THREAD

**Issue by MatteoCampa** [SweeTenTeam/Docs#32]
Redazione della sottosezione **_Gestione della Qualità_** della sezione _Processi di Supporto_ del documento "**_Norme di Progetto_**" e delle relative sottosezioni:
- [x] Scopo
- [x] Descrizione
- [x] Piano di Qualifica
- [x] Testing
- [x] Metriche
- [x] Aspettative

**Comment by orlifera** [comment]
Prima versione completata. Passata in Verify e creata PR #41
