### ISSUE TITLE
Norme di Progetto - Standard ISO/IEC 9126 per la Qualità

### ISSUE THREAD

**Issue by MatteoCampa** [SweeTenTeam/Docs#35]
Redazione della sezione "**_Standard ISO/IEC 9126 per la Qualità_**" del documento "**_Norme di Progetto_**" e delle relative sottosezioni.

**Comment by orlifera** [comment]
- [ ] Funzionalità
- [ ] Affidabilità
- [ ] Usabilità
- [ ] Efficienza
- [ ] Manutentibilità
- [ ] Portabilità
