### ISSUE TITLE
Norme di Progetto - Metriche di Qualità del Processo

### ISSUE THREAD

**Issue by MatteoCampa** [SweeTenTeam/Docs#36]
Redazione della sezione "**_Metriche di Qualità del Processo_**" del documento "**_Norme di Progetto_**" e delle relative sottosezioni.

**Comment by orlifera** [comment]
- [ ] processi primari
    - [ ]  fornitura
    - [ ] sviluppo

- [ ] processi di supporto
    - [ ] documentazione
    - [ ] verifica
    - [ ] gestione della qualità
- [ ] processi organizzativi
    - [ ] gestione dei processi
