### ISSUE TITLE
Norme di Progetto - Metriche di Qualità del Prodotto

### ISSUE THREAD

**Issue by MatteoCampa** [SweeTenTeam/Docs#37]
Redazione della sezione "**_Metriche di Qualità del Prodotto_**" del documento "**_Norme di Progetto_**" e delle relative sottosezioni.

**Comment by orlifera** [comment]
- [ ] funzionalità
- [ ] affidabilità
- [ ] usabilità
- [ ] efficienza
- [ ] manutenibilità
